Entity/FileUpload.php
<?php

namespace Terminalbd\BankReconciliationBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="Terminalbd\BankReconciliationBundle\Repository\FileUploadRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"bank","accountType","transactionDate"}, message="For this date, already file existing,Please try again.")
 * @ORM\Table(name="br_import_file")
 */

class FileUpload
{

    /**
     * @var integer
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue
     */
    private $id;

    /**
     * @var boolean
     * @ORM\Column(type="boolean", nullable = true)
     */
    protected $status = 0;

    /**
     * @var boolean
     * @ORM\Column(type="boolean", nullable = true)
     */
    protected $branch_update_status = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fileName;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    private $type;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    private $accountType;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin\Bank", inversedBy="uploadedFile")
     * @ORM\JoinColumn(referencedColumnName="id")
     */
    private $bank;


    /**
     * @ORM\ManyToOne(targetEntity="Terminalbd\BankReconciliationBundle\Entity\BankAccountCode", inversedBy="uploadedFile")
     * @ORM\JoinColumn(referencedColumnName="id")
     */
    private $BankAccountCode;

    /**
     * @ORM\OneToMany(targetEntity="Terminalbd\BankReconciliationBundle\Entity\BankTransaction", mappedBy="fileUpload")
     * @ORM\JoinColumn(referencedColumnName="id")
     */
    private $transactions;

    /**
     * @ORM\OneToMany(targetEntity="Terminalbd\BankReconciliationBundle\Entity\SubFileUpload", mappedBy="fileUpload")
     * @ORM\JoinColumn(referencedColumnName="id")
     */
    private $subFile;

    /**
     * @ORM\OneToMany(targetEntity="Terminalbd\BankReconciliationBundle\Entity\Reconciliation", mappedBy="fileUpload")
     * @ORM\JoinColumn(referencedColumnName="id")
     */
    private $reconciliations;



    /**
     * @ORM\Column(type="date", nullable = true)
     */
    private $transactionDate;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime", nullable = true)
     */
    private $createdAt;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime", nullable = true)
     */
    private $updatedAt;

    /**
     * @var $uploadedBy
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="fileUpload")
     * @ORM\JoinColumn(referencedColumnName="id")
     */
    private $uploadedBy;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return bool
     */
    public function isStatus(): bool
    {
        return $this->status;
    }

    /**
     * @param bool $status
     */
    public function setStatus(bool $status): void
    {
        $this->status = $status;
    }

    /**
     * @return bool
     */
    public function isBranchUpdateStatus(): bool
    {
        return $this->branch_update_status;
    }

    /**
     * @param bool $branch_update_status
     */
    public function setBranchUpdateStatus(bool $branch_update_status): void
    {
        $this->branch_update_status = $branch_update_status;
    }



    /**
     * @return mixed
     */
    public function getFileName()
    {
        return $this->fileName;
    }

    /**
     * @param mixed $fileName
     */
    public function setFileName($fileName)
    {
        $this->fileName = $fileName;
    }

    /**
     * @return string
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * @param string $type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }


    /**
     * @return string
     */
    public function getAccountType()
    {
        return $this->accountType;
    }

    /**
     * @param string $accountType
     */
    public function setAccountType(string $accountType): void
    {
        $this->accountType = $accountType;
    }




    /**
     * @return BankTransaction
     */
    public function getTransactions()
    {
        return $this->transactions;
    }

    /**
     * @param BankTransaction $transactions
     */
    public function setTransactions($transactions): void
    {
        $this->transactions = $transactions;
    }

    /**
     * @return mixed
     */
    public function getSubFile()
    {
        return $this->subFile;
    }

    /**
     * @param mixed $subFile
     */
    public function setSubFile($subFile): void
    {
        $this->subFile = $subFile;
    }


    
    /**
     * @return mixed
     */
    public function getBank()
    {
        return $this->bank;
    }

    /**
     * @param mixed $bank
     */
    public function setBank($bank): void
    {
        $this->bank = $bank;
    }


    /**
     * @return mixed
     */
    public function getTransactionDate()
    {
        return $this->transactionDate;
    }

    /**
     * @param mixed $transactionDate
     */
    public function setTransactionDate($transactionDate): void
    {
        $this->transactionDate = $transactionDate;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     */
    public function setCreatedAt(\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime $updatedAt
     */
    public function setUpdatedAt(\DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * @return mixed
     */
    public function getUploadedBy()
    {
        return $this->uploadedBy;
    }

    /**
     * @param mixed $uploadedBy
     */
    public function setUploadedBy($uploadedBy): void
    {
        $this->uploadedBy = $uploadedBy;
    }

    /**
     * @return Reconciliation
     */
    public function getReconciliations()
    {
        return $this->reconciliations;
    }


    /**
     * @param Reconciliation $reconciliation
     */
    public function setReconciliations($reconciliation): void
    {
        $this->reconciliations = $reconciliation;
    }

    /**
     * @return mixed
     */
    public function getBankAccountCode()
    {
        return $this->BankAccountCode;
    }

    /**
     * @param mixed $BankAccountCode
     */
    public function setBankAccountCode($BankAccountCode)
    {
        $this->BankAccountCode = $BankAccountCode;
    }








}

Controller/FileUploadController.php
<?php


namespace Terminalbd\BankReconciliationBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Terminalbd\BankReconciliationBundle\Entity\BankAccountCode;
use Terminalbd\BankReconciliationBundle\Entity\BankTransaction;
use Terminalbd\BankReconciliationBundle\Entity\FileUpload;
use Terminalbd\BankReconciliationBundle\Entity\SubFileUpload;
use Terminalbd\BankReconciliationBundle\Form\FileUploadFormType;
use Symfony\Contracts\Translation\TranslatorInterface;
use Terminalbd\BankReconciliationBundle\Form\SubFileUploadFormType;


/**
 * Class FileUploadController
 * @package Terminalbd\BankReconciliationBundle\Controller
 * @Route("/file")
 */
class FileUploadController extends AbstractController
{
    /**
     * @Security("is_granted('ROLE_DEVELOPER') or is_granted('ROLE_BR_ADMIN')")
     * @Route("/bank-statement-upload", name="br_bank_statement_upload")
     */
    public function bankStatementUpload(Request $request, TranslatorInterface $translator)
    {
        set_time_limit(0);
        ini_set('memory_limit', '5000M');

        $fileUpload = new FileUpload();
        $allowFileType = ['xlsx'];

        $data = $this->getDoctrine()->getRepository(FileUpload::class)
            ->findBy(['type' => 'bank-statement'],['id' => 'desc']);
        $form = $this->createForm(FileUploadFormType::class, $fileUpload);
        $form->handleRequest($request);

        /*$exist = $this->getDoctrine()->getRepository(FileUpload::class)->findOneBy(array('bank'=>$fileUpload->getBank(),'accountType'=>$fileUpload->getAccountType(),'transactionDate'=>$fileUpload->getTransactionDate()));*/
        if ($form->isSubmitted() && $form->isValid()){
            $transactionDate = $fileUpload->getTransactionDate()->format('d-m-Y');
            /*if($exist){
                $this->addFlash('error', $translator->trans('File Already Uploaded!'));
                return $this->redirectToRoute('br_bank_statement_upload');
            }else{*/
                $uploadedFile = $form['UploadFile']->getData();
                if (in_array($uploadedFile->getClientOriginalExtension(), $allowFileType)){
                    $em = $this->getDoctrine()->getManager();
                    $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);

                    $newFileName = $form['bank']->getData()->getSlug() . '_TD_' . $transactionDate . '_CD_' . date('d-m-Y') . '-' . time() . '.' . $uploadedFile->getClientOriginalExtension();
                    $uploadDir = $this->get('kernel')->getProjectDir() . '/public/uploads/reconciliation/';
                    $uploadedFile->move(
                        $uploadDir,
                        $newFileName
                    );

                    $accountCode = $this->getDoctrine()->getRepository(BankAccountCode::class)->findOneBy(['bank'=>$form['bank']->getData()->getId(),'accountType'=>$form['accountType']->getData()]);
                    if ($accountCode) {
                        $code = $this->getDoctrine()->getRepository(BankAccountCode::class)->find($accountCode->getId());
                    }else{
                        $code = null;
                    }

                    $fileUpload->setFileName($newFileName);
                    $fileUpload->setType('bank-statement');
                    $fileUpload->setCreatedAt( new \DateTime('now'));
                    $fileUpload->setBankAccountCode($code);
                    $em->persist($fileUpload);
                    $em->flush();

                    $this->addFlash('success', $translator->trans('File Uploaded Successfully!'));
                    return $this->redirectToRoute('br_bank_statement_list');
                }else{
                    $this->addFlash('error', $translator->trans('Invalid File Format!'));
                    return $this->redirectToRoute('br_bank_statement_upload');
                }
//            }

        }
        return $this->render('@TerminalbdBankReconciliation/fileUpload/bank-statement.html.twig',[
            'form' => $form->createView(),
            'data' => $data,
        ]);
    }



    /**
     * @Security("is_granted('ROLE_DEVELOPER') or is_granted('ROLE_BR_ADMIN')")
     * @Route("/bank-statement-list", name="br_bank_statement_list")
     */
    public function bankStatementList(Request $request)
    {
        set_time_limit(0);
        ini_set('memory_limit', '5000M');

        $data = $this->getDoctrine()->getRepository(FileUpload::class)->findBy(['type' => 'bank-statement'],['id' => 'desc']);

        return $this->render('@TerminalbdBankReconciliation/fileUpload/bank-statement-list.html.twig',[
            'data' => $data,
        ]);
    }

    /**
     * @Security("is_granted('ROLE_DEVELOPER') or is_granted('ROLE_BR_ADMIN')")
     * @Route("/{id}/delete", name="br_file_delete")
     */
    public function delete(FileUpload $file)
    {
        $uploadDir = $this->get('kernel')->getProjectDir() . '/public/uploads/reconciliation/';
        $subUploadDir = $this->get('kernel')->getProjectDir() . '/public/uploads/reconciliation/sub-file/';

        if (file_exists($uploadDir.$file->getFileName())){
            $filesystem = new Filesystem();
            $filesystem->remove($uploadDir.$file->getFileName());
        }

        $subFile = $this->getDoctrine()->getRepository(SubFileUpload::class)->findAll(['fileUpload'=>$file]);
        if ($subFile){
            foreach ($subFile as $value){
                if (file_exists($subUploadDir.$value->getSubFileName())){
                    $filesystem = new Filesystem();
                    $filesystem->remove($subUploadDir.$value->getSubFileName());
                }
            }
        }

        $em = $this->getDoctrine()->getManager();
        $em->remove($file);
        $em->flush();

        $this->addFlash('success','File has been deleted!');
        return $this->redirectToRoute('br_bank_statement_upload');
    }

    /**
     * @Security("is_granted('ROLE_DEVELOPER') or is_granted('ROLE_BR_ADMIN')")
     * @Route("/custom-statement-create", name="br_custom_statement_create")
     */
    public function customStatementCreate(Request $request)
    {
        $fileUpload = new FileUpload();
        $form = $this->createForm(FileUploadFormType::class,$fileUpload)->remove('UploadFile');
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $accountCode = $this->getDoctrine()->getRepository(BankAccountCode::class)->findOneBy(['bank'=>$form['bank']->getData()->getId(),'accountType'=>$form['accountType']->getData()]);
            if ($accountCode) {
                $code = $this->getDoctrine()->getRepository(BankAccountCode::class)->find($accountCode->getId());
            }else{
                $code = null;
            }

            $transactionDate = $fileUpload->getTransactionDate()->format('d-m-Y');
            $em = $this->getDoctrine()->getManager();
            $fileUpload->setType('bank-statement');
            $fileUpload->setBankAccountCode($code);
            $fileUpload->setCreatedAt( new \DateTime('now'));
            $fileUpload->setStatus(1);
            $em->persist($fileUpload);
            $em->flush();

            $this->addFlash('success','Custom Statement Added Successfully!');
            return $this->redirectToRoute('br_bank_statement_list');
        }
        return $this->render('@TerminalbdBankReconciliation/fileUpload/custom-statement-create.html.twig',[
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Security("is_granted('ROLE_DEVELOPER') or is_granted('ROLE_BR_ADMIN')")
     * @Route("/transacton/{id}/sub/file/upload", name="br_transaction_add_sub_file")
     */
    public function transactionSubFileUpload(Request $request, FileUpload $fileUpload)
    {
        set_time_limit(0);
        ini_set('memory_limit', '5000M');
        $bank = $fileUpload->getBank();

        $form = $this->createForm(SubFileUploadFormType::class,$fileUpload)->remove('bank');
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $subFileUpload = new SubFileUpload();
            $allowFileType = ['xlsx'];
            $uploadedFile = $form['UploadFile']->getData();
            if (in_array($uploadedFile->getClientOriginalExtension(), $allowFileType)) {
                $em = $this->getDoctrine()->getManager();
                $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
                $findSubFile = $this->getDoctrine()->getRepository(SubFileUpload::class)->findOneBy(['fileUpload'=>$fileUpload->getId()],['id'=>'desc']);
                if ($findSubFile){
                    $subFileSL = $findSubFile->getBatchName();
                    $str = substr(strrchr($subFileSL, '-'), 1);
                    $subFileSL = $str+1;
                }else{
                    $subFileSL = 1;
                }
                $transactionDate = $fileUpload->getTransactionDate()->format('d-m-Y');
                $batchNumberSlug = $transactionDate.'-'.$fileUpload->getId().'-'.$subFileSL;
//                $batchNumber = $transactionDate.'#'.$fileUpload->getId().'-'.$subFileSL;

                $fileName = substr($fileUpload->getFileName(), 0, strpos($fileUpload->getFileName(), '_'));
                $newFileName = $fileName . '_TD_' . $transactionDate . '_CD_' . date('d-m-Y') . '-BN-' . $batchNumberSlug . '.' . $uploadedFile->getClientOriginalExtension();
                $uploadDir = $this->get('kernel')->getProjectDir() . '/public/uploads/reconciliation/sub-file';
                $uploadedFile->move(
                    $uploadDir,
                    $newFileName
                );
            }

Resources/views/fileUpload/add-sub-file.html.twig
{% extends 'admin/layout.html.twig' %}

{% block body %}

    <div class="row">
        <div class="card">
            <div class="card-header">
                <h5>Bank Sub statement Upload</h5>
                <div class="card-header-right">
                    <div class="btn-group btn-group-sm" role="group" aria-label="Button group with nested dropdown">
                        <a href="{{ path('br_custom_statement_create') }}" id="createForm"  class="btn btn-sm  green-bg white-font"><i class="fa fa-plus"></i>{{ 'Custom Statement'|trans }}</a>
                        <a href="{{ path('br_bank_statement_list') }}" class="btn btn-sm gray-bg white-font"><i class="fa fa-th-large"></i>{{ 'Bank Statement'|trans }}</a>
                        <a href="{{ path('br_bank_statement_upload') }}" id="createForm"  class="btn btn-sm  green-bg white-font"><i class="fa fa-plus"></i>{{ 'Upload Statement'|trans }}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 offset-3">
            <div class="card">
                <div class="card-body">
                    {#<form action="{{ path('br_transaction_add_file',{id: fileData.id}) }}" method="post">
                        <label class="control-label required" for="file_upload_form_UploadFile">Upload File Here:</label>
#}{#                        <input type="file" name="sub_file" help="Please upload only excel file!" mapped="false" class="form-control" style="padding-top: 7px !important; padding-bottom: 30px !important;">#}{#
                        <input type="file" id="file_upload_form_UploadFile" name="file_upload_form[UploadFile]" required="required" class="form-control" style="padding-top: 7px !important; padding-bottom: 30px !important;">
                        <span id="file_upload_form_UploadFile_help" class="text-secondary help-block">Please upload only excel file!</span>
                        <button type="submit" id="file_upload_form_Submit" name="file_upload_form" class="btn btn-block btn-info mt-3 btn">Upload</button>
                    </form>#}
                    {{ form_start(form) }}
                    {#{{ form_label(form.bank,'Bank Name:') }}
                    {{ form_widget(form.bank) }}
                    {{ form_errors(form.bank) }}

                    <input type="hidden" name="bank" value="{{ fileData.bank.id }}">#}
                    <label class="mt-3 control-label required" for="sub_file_upload_form_accountType">Bank Name:</label>
                    <input type="text" value="{{ fileData.bank.name }}" class="form-control" readonly>
                    {{ form_label(form.accountType,'Account Type:', {'label_attr':{'class': 'mt-3'}}) }}
                    {{ form_widget(form.accountType) }}
                    {{ form_errors(form.accountType) }}
                    {{ form_label(form.transactionDate,'Transaction Date:', {'label_attr':{'class': 'mt-3'}}) }}
                    {{ form_widget(form.transactionDate,{'id':'inputMonth','attr':{'class':'mb-3'}}) }}
                    {{ form_errors(form.transactionDate) }}
                    {{ form_label(form.UploadFile,'Upload File Here:') }}
                    {{ form_widget(form.UploadFile,{'attr':{'class':'form-control','style':'padding-top: 7px !important; padding-bottom: 30px !important;'}}) }}
                    {{ form_help(form.UploadFile,{'help_attr':{'class':'text-secondary'}}) }}
                    {{ form_widget(form.Submit,{'attr':{'class':'btn btn-block btn-info mt-3'},'label':'Upload'}) }}

                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>


{% endblock %}
{% block cssBlock %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('assets/module/css/app.css') }}">
    <style>
        /*.ui-datepicker-calendar{display: none}*/
    </style>
{% endblock  %}
{% block javascripts %}
    {{ parent() }}
    <script type="application/javascript" src="{{ asset('assets/module/js/app.js') }}"></script>
{% endblock  %}
{% block documentready %}
    {{ parent() }}



{#    $('#inputMonth').datepicker({#}
{#    changeMonth: true,#}
{#    changeYear: true,#}
{#    dateFormat: 'MM,yy',#}

{#    onClose: function() {#}
{#    var iMonth = $("#ui-datepicker-div .ui-datepicker-month :selected").val();#}
{#    var iYear = $("#ui-datepicker-div .ui-datepicker-year :selected").val();#}
{#    $(this).datepicker('setDate', new Date(iYear, iMonth, 1));#}
{#    },#}

{#    beforeShow: function() {#}
{#    if ((selDate = $(this).val()).length > 0)#}
{#    {#}
{#    iYear = selDate.substring(selDate.length - 4, selDate.length);#}
{#    iMonth = jQuery.inArray(selDate.substring(0, selDate.length - 5), $(this).datepicker('option', 'monthNames'));#}
{#    $(this).datepicker('option', 'defaultDate', new Date(iYear, iMonth, 1));#}
{#    $(this).datepicker('setDate', new Date(iYear, iMonth, 1));#}
{#    }#}
{#    }#}
{#    });#}

    $('#datatable').DataTable( {
    pageLength: 25,
    columnDefs: [ {
    targets: -1,
    orderable: false
    }],
    });
{% endblock %}

Resources/views/fileUpload/bank-statement-list.html.twig
{% extends 'admin/layout.html.twig' %}

{% block body %}

    <div class="row">
        <div class="card">
            <div class="card-header">
                <h5>Bank statement Upload</h5>
                <div class="card-header-right">
                    <div class="btn-group btn-group-sm" role="group" aria-label="Button group with nested dropdown">
                        <a href="{{ path('br_custom_statement_create') }}" id="createForm"  class="btn btn-sm  green-bg white-font"><i class="fa fa-plus"></i>{{ 'Custom Statement'|trans }}</a>
                        <a href="{{ path('br_bank_statement_list') }}" class="btn btn-sm gray-bg white-font"><i class="fa fa-th-large"></i>{{ 'Bank Statement'|trans }}</a>
                        <a href="{{ path('br_bank_statement_upload') }}" id="createForm"  class="btn btn-sm  green-bg white-font"><i class="fa fa-plus"></i>{{ 'Upload Statement'|trans }}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card p-3">
                <table class="table table-bordered table-striped" id="datatable">
                    <thead class="thead-dark">
                    <tr>
                        <th width="5%" class="text-center">{{ 'S/N'|trans }}</th>
                        <th width="15%">{{ 'Bank Name'|trans }}</th>
                        <th width="25%">{{ 'File Name'|trans }}</th>
                        <th width="10%">{{ 'Type'|trans }}</th>
                        <th width="10%">{{ 'Transaction Date'|trans }}</th>
{#                        <th width="10%">{{ 'Deposit'|trans }}</th>#}
{#                        <th width="10%">{{ 'Reconciliation Amount'|trans }}</th>#}
{#                        <th width="10%">{{ 'Difference Amount'|trans }}</th>#}
{#                        <th width="10%" class="text-center">{{ 'Status'|trans }}</th>#}
{#                        <th width="10%">{{ 'Created Date'|trans }}</th>#}
                        <th width="10%" class="text-center"><i class="feather icon-settings"></i></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if data is defined and data is not empty %}
                        {% for file in data %}
{#                            <tr>#}
{#                                <td></td>#}
{#                                <td></td>#}
{#                                <td>{{ file.fileName }}</td>#}
{#                                <td></td>#}
{#                                <td></td>#}
{#                                <td>{{ file.depositeTotal }}</td>#}
{#                            </tr>#}
                            <tr>
                                <td class="text-center">{{ loop.index }}</td>
                                <td>
                                    <a href="{{ path('br_transaction_download',{id: file.id}) }}">
                                        {{ file.bank.name|capitalize|default('') }}
                                    </a>
                                </td>
{#                                <td>{{ file.bankName|capitalize|default('') }}</td>#}
                                <td><a href="{{ asset('/uploads/reconciliation/' ~ file.fileName) }}" download>{{ file.fileName|default('') }}</a></td>
                                <td>{{ file.accountType|default('') }}</td>
                                <td>{{ file.transactionDate|date('d-m-Y')|default('') }}</td>
{#                                <td></td>#}
{#                                <td></td>#}
{#                                <td></td>#}
{#                                <td class="text-center">{{ file.status > 0 ? 'Yes' : 'No' }}</td>#}
{#                                <td class="text-center">{{ file.createdAt|date('d-m-Y') }}</td>#}
                                <td class="text-right">
                                    <div class="btn-group" role="group">
                                        {% if file.status == 0 %}
                                            <a class="btn btn-mini bg-primary white-font" href="{{ path('br_transaction_import',{id: file.id}) }}"><i class="feather icon-upload"></i> Import</a>
                                        {% endif %}
                                        {% if file.status > 0 %}
                                            {% if file.branchUpdateStatus > 0 %}
                                            <a class="btn btn-mini green-bg white-font" href="{{ path('br_transaction_add_sub_file',{id: file.id}) }}"><i class="fa fa-plus-circle"></i> Add Sub File </a>
                                                {% endif %}

                                            <a class="btn btn-mini purple-bg white-font" href="{{ path('br_transaction_branch_update',{id: file.id}) }}"><i class="feather icon-upload"></i> {% if file.fileName is defined and file.fileName is not empty %} Update Branch {% else %}Sync{% endif %}</a>
                                            {% if file.branchUpdateStatus > 0 or file.fileName is empty  %}
                                                <a class="btn btn-mini orange-bg white-font" href="{{ path('br_transaction_add',{id: file.id}) }}"><i class="fa fa-plus-circle"></i> Add Transaction</a>
                                            {% endif %}

                                        {% endif %}
                                        <a data-action="{{ path('br_file_delete',{id: file.id}) }}" class="btn  btn-transparent btn-mini red-font remove" href="javascript:"><i class="fa fa-remove"></i></a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="6" class="text-center font-weight-bold">{{ "No record Found!"|trans }}</td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>


{% endblock %}
{% block cssBlock %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('assets/module/css/app.css') }}">
    <style>
        /*.ui-datepicker-calendar{display: none}*/
    </style>
{% endblock  %}
{% block javascripts %}
    {{ parent() }}
    <script type="application/javascript" src="{{ asset('assets/module/js/app.js') }}"></script>
{% endblock  %}
{% block documentready %}
    {{ parent() }}



    {#    $('#inputMonth').datepicker({#}
    {#    changeMonth: true,#}
    {#    changeYear: true,#}
    {#    dateFormat: 'MM,yy',#}

    {#    onClose: function() {#}
    {#    var iMonth = $("#ui-datepicker-div .ui-datepicker-month :selected").val();#}
    {#    var iYear = $("#ui-datepicker-div .ui-datepicker-year :selected").val();#}
    {#    $(this).datepicker('setDate', new Date(iYear, iMonth, 1));#}
    {#    },#}

    {#    beforeShow: function() {#}
    {#    if ((selDate = $(this).val()).length > 0)#}
    {#    {#}
    {#    iYear = selDate.substring(selDate.length - 4, selDate.length);#}
    {#    iMonth = jQuery.inArray(selDate.substring(0, selDate.length - 5), $(this).datepicker('option', 'monthNames'));#}
    {#    $(this).datepicker('option', 'defaultDate', new Date(iYear, iMonth, 1));#}
    {#    $(this).datepicker('setDate', new Date(iYear, iMonth, 1));#}
    {#    }#}
    {#    }#}
    {#    });#}

    $('#datatable').DataTable( {
    pageLength: 25,
    columnDefs: [ {
    targets: -1,
    orderable: false
    }],
    });
{% endblock %}